### ISSUE TITLE
Add chatbot

### ISSUE THREAD

**Issue by Sanket1308** [Sanket1308/bots-collection#3]
- Create a folder for your chatbot with appropriate name
- Add chatbot code in it
- Add feature.md file in same folder explaining the technology, features and use of your chatbot. 
- Add images of output showing chatbot feature.
- Create PR

**Comment by ramyashreeshetty** [comment]
can i work on this?

**Comment by Sanket1308** [comment]
Go ahead! Contribute well🚀
